# Generated by Django 5.2.1 on 2025-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdetails',
            name='content_rating',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
